public  class MapDemo {
    public static void mapStringInteger(){
        //Map -  caseSensitive, overide!doll
        //string -> key
        //value-> integer
        //map<key DT, value DT>
        map<string, integer> map1= new map<string, integer>();
        //in map, we PUT key value pair
        map1.put('one', 101);
        map1.put('two', 202);
        map1.put('three', 303);
        map1.put('one', 1001);
        system.debug(map1);



        map<string, string> map2;
        map<string,integer> map3;
        map<integer, string> map4;
        map<boolean, string> map5;
        
    }

    
       
}