Emplyee newE = new Emplyee();
newE.setName ('Nick Bennett ');
newE.setSalary(110000);

string newEName = newE.getName();
decimal newESalary = newE.getSalary();
system.debug(newEName + 'salary is '+newESalary);

Emplyee newE1 = new Emplyee();
newE1.setName ('Jessica Alba ');
newE1.setSalary(200000);

string newE1Name = newE1.getName();
decimal newE1Salary = newE1.getSalary();
system.debug(newE1Name + 'salary is '+newE1Salary);