Listdemo2.iterateList();

List<integer> moreList = new list<integer>();
moreList.add(90);
moreList.add(10);

//Listdemo2.add(moreList);
integer sum1 = Listdemo2.add(moreList);
system.debug('Sum1 is '+ sum1);

list<string> ls = new list<string>{'list', 'set', 'map', 'array'};
ls.add('methods');
ls.add('constructor');
Listdemo2.iterateListString(ls);

list<string> ls = new list<string>{'list', 'set', 'map', 'array'};
system.debug(calculator.add(ls));

ListDemo2.iterateListString11();
